### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by TrenShadow** [jkjoschua/poe-ladder-tracker-java#3]
JRE v8-131 on Windows 10

have tried double-clicking on the jar, and running from command line multiple times, on both standard and administrator accounts. Initial setup window loads, I've tried multiple combos of league/character, and it just says Updating.... 

running from command line produces this (and keeps going until I press Ctrl-C, or close the window:

C:\Ladder Tracker>java -jar Ladder-Tracker-v2.0.jar
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at CSVLinkCreator.create(CSVLinkCreator.java:40)
        at GUILadderTracker$1.run(GUILadderTracker.java:180)

^C
C:\Ladder Tracker>

**Comment by jkjoschua** [comment]
Looks like an internal java script timeout (maybe your connection to the webservers is bad).
I extended the timeout value in the newest release. So please download the new version and try again.
If there is still an error try the new API mode.

**Comment by TrenShadow** [comment]
New version works in both CSV and API mode.

Thanks :)
